### PR TITLE
Added virtual environment support to the task decorator

### PR DESCRIPTION
**Pull request by carolinepacheco**
Added virtual environment support.

### CODE REVIEW

**Review by Hiba-Alili — APPROVED** [review]

**Review by dianajlailaty — APPROVED** [review]

**Comment by fviale** [comment]
@carolinepacheco 

I don't understand what is done here regarding virtual environments

For info there is a workflow example that enables virtual env on a cpython task:
https://github.com/ow2-proactive/proactive-examples/blob/master/GetStarted/resources/catalog/Python_VirtualEnv.xml

**Comment by fviale** [comment]
this workflow example involves several important things
 - setting System Environment Variables in the forked task
 - using a fork environment script that prepare the virtual env folder, etc

**Comment by andrewssobral** [comment]
@fviale The Python virtual environment support is already integrated into the Python SDK. I followed the workflow template you mentioned to implement it directly within the SDK. What Caroline is doing here is extending this support to the recently created Python decorators, specifically @task and @job. You can find an example of this implementation here:
[Demo of basic decorators](https://github.com/ow2-proactive/proactive-python-client-examples/blob/main/demo_decorators_basic.py)
New example to be added:
https://github.com/ow2-proactive/proactive-python-client-examples/pull/8/files

**Comment by fviale** [comment]
thanks @andrewssobral for the clarification

**Review by andrewssobral — APPROVED** [review]

**Pull request merged**
